### PR TITLE
[WIP] Fix segfault on node exit during wallet rpc test

### PR DESCRIPTION
**Pull request by Justaphf**
I have tested and all standard rpc tests and make check pass without the node shutdown segfault on my Debian 8.5 machine.  Need someone who can build from source on OS X to verify everything works on Mac.

### CODE REVIEW

**Comment by digitsu** [comment]
I don't have a osx system that can run a node right now as I'm travelling, but it at least builds clean on my osx 10.11.6

**Comment by ptschip** [comment]
this works fine on ubuntu 16.04

compiled on windows 10 no problems.

**Comment by nomnombtc** [comment]
at least with `--enable-debug` bitcoin-qt still core dumps on exit here with this commit :(

```
#0  0x00007f6c7a933fc8 in malloc_consolidate () at /lib64/libc.so.6
#1  0x00007f6c7a935c18 in _int_free () at /lib64/libc.so.6
#2  0x00007f6c7a9395bc in free () at /lib64/libc.so.6
#3  0x00005615b0ccb720 in CNetCleanup::~CNetCleanup() (this=0x5615b19fccd8 <cnet_instance_cleanup>, __in_chrg=<optimized out>) at net.cpp:2283
#4  0x00007f6c7a8ed190 in __run_exit_handlers () at /lib64/libc.so.6
#5  0x00007f6c7a8ed1ea in  () at /lib64/libc.so.6
#6  0x00007f6c7a8d3357 in __libc_start_main () at /lib64/libc.so.6
#7  0x00005615b094951a in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by ptschip** [comment]
@nomnombtc   are you running on windows or linux or ?

can you try doing this, on line 80 or thereabouts in unlimited.cpp  replace the following:

CNetCleanup cnet_instance_cleanup **attribute**((init_priority(110)));  // Must construct after statistics, because CNodes use statistics.  In particular, seg fault on osx during exit because constructor/destructor order is not guaranteed between modules in clang.

with

CNetCleanup cnet_instance_cleanup; 

and try again

**Comment by nomnombtc** [comment]
@ptschip I am running linux 64bit, trying this now.

**Comment by gandrewstone** [comment]
I'm not able to reproduce this seg fault.  But it makes sense that CNetCleanup should be the first destructor to be run (because it disconnects from peer nodes).  And that means putting its init_priority higher and moving it below all the other global decls.

**Comment by nomnombtc** [comment]
@ptschip still the same,  backtrace looks exactly like the one above. I changed it so:

```
-CNetCleanup cnet_instance_cleanup __attribute__((init_priority(65535)));
+CNetCleanup cnet_instance_cleanup;
```

@gandrewstone are you also running with `--enable-debug`?

**Comment by gandrewstone** [comment]
Ok that free failure looks like it is on delete semOutbound;
I suppose that semOutbound may never get allocated (if you make no outbound connections).
Try this at net.cpp:2283
if (semOutbound) delete semOutbound;
and net.cpp:2286
if (semOutboundAddNode) delete semOutboundAddNode;

**Comment by nomnombtc** [comment]
@gandrewstone I am sorry it is still the same here:

```
Thread 1 (Thread 0x7f7e3f509780 (LWP 28348)):
#0  0x00007f7e3a401fc8 in malloc_consolidate () at /lib64/libc.so.6
#1  0x00007f7e3a403c18 in _int_free () at /lib64/libc.so.6
#2  0x00007f7e3a4075bc in free () at /lib64/libc.so.6
#3  0x00005643dbf9e72c in CNetCleanup::~CNetCleanup() (this=0x5643dcccfcd8 <cnet_instance_cleanup>, __in_chrg=<optimized out>) at net.cpp:2283
#4  0x00007f7e3a3bb190 in __run_exit_handlers () at /lib64/libc.so.6
#5  0x00007f7e3a3bb1ea in  () at /lib64/libc.so.6
#6  0x00007f7e3a3a1357 in __libc_start_main () at /lib64/libc.so.6
#7  0x00005643dbc1c51a in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by gandrewstone** [comment]
are you sure that you are recompiling?  Try commenting the line out entirely (net.cpp:2283)...

**Comment by nomnombtc** [comment]
@gandrewstone yeah pretty sure, after every change I always run make clean and configure/make again, and then I run the binary like this `./src/qt/bitcoin-qt`. Ok so that we don't get confused: this is now 0.12.1bu+this pull+ the 2 if's added in net.cpp and then line 2283 commented out (and build with --enable-debug):

```
Thread 1 (Thread 0x7f5d2ff7b780 (LWP 50146)):
#0  0x00007f5d2ae73fc8 in malloc_consolidate () at /lib64/libc.so.6
#1  0x00007f5d2ae75c18 in _int_free () at /lib64/libc.so.6
#2  0x00007f5d2ae795bc in free () at /lib64/libc.so.6
#3  0x0000558d3519238f in __gnu_cxx::new_allocator<unsigned char>::deallocate(unsigned char*, unsigned long) (this=0x7f5cde96ed58, __p=0x7f5cdd90dbf0 "") at /usr/include/c++/5.4.0/ext/new_allocator.h:110
#4  0x0000558d3518ec59 in __gnu_cxx::__alloc_traits<std::allocator<unsigned char> >::deallocate(std::allocator<unsigned char>&, unsigned char*, unsigned long) (__a=..., __p=0x7f5cdd90dbf0 "", __n=359439) at /usr/include/c++/5.4.0/ext/alloc_traits.h:185
#5  0x0000558d3518bc33 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_deallocate(unsigned char*, unsigned long) (this=0x7f5cde96ed58, __p=0x7f5cdd90dbf0 "", __n=359439) at /usr/include/c++/5.4.0/bits/stl_vector.h:178
#6  0x0000558d3518a0ff in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::~_Vector_base() (this=0x7f5cde96ed58, __in_chrg=<optimized out>) at /usr/include/c++/5.4.0/bits/stl_vector.h:160
#7  0x0000558d35188c23 in std::vector<unsigned char, std::allocator<unsigned char> >::~vector() (this=0x7f5cde96ed58, __in_chrg=<optimized out>) at /usr/include/c++/5.4.0/bits/stl_vector.h:425
#8  0x0000558d353c5fa3 in CBloomFilter::~CBloomFilter() (this=0x7f5cde96ed58, __in_chrg=<optimized out>) at bloom.h:45
#9  0x0000558d35408bd4 in CRollingBloomFilter::~CRollingBloomFilter() (this=0x7f5cde96ed28, __in_chrg=<optimized out>) at bloom.h:117
#10 0x0000558d354c872d in CNode::~CNode() (this=0x7f5cde96e8d0, __in_chrg=<optimized out>) at net.cpp:2667
#11 0x0000558d354c5616 in CNetCleanup::~CNetCleanup() (this=0x558d361f6cd8 <cnet_instance_cleanup>, __in_chrg=<optimized out>) at net.cpp:2288
#12 0x00007f5d2ae2d190 in __run_exit_handlers () at /lib64/libc.so.6
#13 0x00007f5d2ae2d1ea in  () at /lib64/libc.so.6
#14 0x00007f5d2ae13357 in __libc_start_main () at /lib64/libc.so.6
#15 0x0000558d3514351a in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by gandrewstone** [comment]
ok unfortunately that was exactly what I'd expect to see if you are doing everything right (but your heap is corrupted).  What exact linux distro and version are you running, have you "updated it", what's the contents of your ~/.bitcoin/bitcoin.conf file (if you changed anything, and don't give me your rpc user and password), and are you using any flags other than --enable-debug (I will try to reproduce).

**Comment by nomnombtc** [comment]
Hmm I run slackware64-current, for sure have a few custom packages and the newest kernel (4.8.4), but I also tried it in a slackware-14.2 (64bit) vm with stock kernel and produced the same backtrace there.

Also note I am not really running the tests, I just exit bitcoin-qt by clicking the [x].
configure options: `./configure --with-gui=qt4 --enable-debug`
bitcoin.conf:

```
rpcuser=bitcoinrpc
rpcpassword=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
server=1
listenonion=1
torcontrol=127.0.0.1:9151
torpassword=/home/mps/tor-browser_en-US/Browser/TorBrowser/Data/Tor/control_auth_cookie
whitelist=127.0.0.1/8
discover=1
listen=1
rpcallowip=192.168.2.0/24
addnode=5.135.186.15
mempoolreplacement=0
excessiveblocksize=8000000
excessiveacceptdepth=6
```

**Comment by nomnombtc** [comment]
I did some more tests without `--enable-debug` this time, but it still doesn't seem to work correctly here. Used `wallet.py` test 10 times in a row, and they all said "test successful" but my /tmp dir is now full with coredumps (I had removed all old core dumps before running the test).

```
$ ls -l core_bitcoin-shutoff.* | wc -l
72
```

Also on run 9 it did this (which also seems to happen at "stopping nodes"):

```
Initializing test directory /tmp/test7mZaJP
Mining blocks...
Stopping nodes
*** Error in `bitcoind': corrupted double-linked list: 0x00005589f17173a0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x776f4)[0x7f9b328366f4]
/lib64/libc.so.6(+0x7e838)[0x7f9b3283d838]
/lib64/libc.so.6(+0x801e8)[0x7f9b3283f1e8]
/lib64/libc.so.6(cfree+0x4c)[0x7f9b32842c1c]
bitcoind(+0x12b981)[0x5589ef11a981]
bitcoind(+0x12bf7a)[0x5589ef11af7a]
/lib64/libc.so.6(+0x39fb8)[0x7f9b327f8fb8]
/lib64/libc.so.6(+0x3a005)[0x7f9b327f9005]
/lib64/libc.so.6(__libc_start_main+0xf7)[0x7f9b327df7d7]
bitcoind(+0x44c59)[0x5589ef033c59]
[...]
Cleaning up
Tests successful
```

So I don't know something still seems wrong there somehow, at least on my system.

**Comment by ftrader** [comment]
The segfaults-on-exit do not affect the results of the tests AFAIK. So it's expected that tests pass, but there is ugly backtrace output when the bitcoind's are terminated, and core dumps on systems where those are set to be produced. I don't think this indicates something wrong with your system in particular.

**Comment by sickpig** [comment]
@Justaphf great work. the PR fix the issue tests I made on ubuntu 16.05 and debian 8 (both amd64). 

need a rebase due to e7c208fecdc7556bc2e983314c67c7539c7eaa9a

**Comment by Justaphf** [comment]
Rebased and retested on my Debian 8.5 test machine.  Will need to install a Slackware VM to try and debug @nomnombtc's issue.

**Comment by nomnombtc** [comment]
@Justaphf not sure it has something to do with slackware, but I have core dumps enabled, maybe this causes it. For example I have this app which never caused problems (livestreamer-twitch-gui) and since I have core dumps enabled I often find a dump in /tmp which complains about segfault.

**Comment by nomnombtc** [comment]
@Justaphf ok it seems there were some changes here, I noticed the new file `globals.cpp`. I tested it again, this time in a debian 8.6 jessie (64bit) vm with KDE and it still is weird, but different from what I got on slackware earlier :)

 First with core dumps disabled (core file size=0). compiled with `./configure --with-gui=qt4 --with-incompatible-bdb`, then I run wallet.py in qa/rpc-tests.

I did run it 3 times, and on the 3rd run this was in dmesg:
`[12256.986657] traps: bitcoin-shutoff[28352] general protection ip:7f1815927614 sp:7ffdcc4a0218 error:0 in libc-2.19.so[7f18158ab000+1a1000]`

it also did this every time while running wallet.py (but is maybe not related to node shutdown):

```
Mining blocks...
*** Error in `bitcoind': double free or corruption (!prev): 0x00007f4fb4020870 ***
*** Error in `bitcoind': double free or corruption (fasttop): 0x00007fe84401ac80 ***
```

Then I enabled core dumps (set core to unlimited in `/etc/security/limits.conf`) reboot, and
now it also created 2 core dumps on the first run.  

Here is a pastebin with backtrace: http://paste.debian.net/890200/

So while I am not getting segfaults like earlier, the core dumps say it is SIGABRT now :/

**Comment by Justaphf** [comment]
@nomnombtc I am looking into this further.  I see that you were running TOR which I hadn't been testing (though I'm not sure that has anything to do with it).  Will try some test cases with that.
As for having core dumps enabled, that shouldn't be causing the crash, just reporting it.  Having core dumps off would just mean the crash happened silently and since it's during shutdown, which didn't cause the test to fail, would appear as if everything was OK.

**Comment by Justaphf** [comment]
@nomnombtc Thanks for the backtrace.  Looks like the issue is occurring in a different location on your Debian test machine.  It also looks like there were some additional changes merged earlier today which I haven't rebased yet that may also affect your results as they touch on the orphaned transactions map, which is where your backtrace is pointing.

Were you testing with the latest 0.12.1bu branch plus this PR, or just this PR?

**Comment by nomnombtc** [comment]
@Justaphf latest 0.12.1bu plus this PR (cherry-picked the commit). I can also try again with git cloning it from your repo.

**Comment by ptschip** [comment]
i would clone the whole repo on this one...there are quite a few changes
you may not have picked up.

**Comment by Justaphf** [comment]
@nomnombtc I would suggest cloning the 0.12.1bu branch off of the BitcoinUnlimited repo, not mine, as I have not pushed a rebase yet.  The current iteration of this PR is a 1 word change so it would be easy to reapply on top of the main branch.

**Comment by nomnombtc** [comment]
@ptschip @Justaphf I cloned from Justaphf repo (branch: 12.1initpriority) and finally some good news, at least in this debian vm wallet.py test runs fine now without problems, and no core dump. So it seems those other recent commits here in 0.12.1bu break it again but in a different way :+1:

**Comment by nomnombtc** [comment]
@Justaphf this is getting really strange, it works fine in my debian vm now if I use your repo. But also with your repo, same git HEAD tag in both vm's (7e5f8b0), on the slackware64-14.2 vm it still segfaults and core dumps. backtrace still looks the same like the one from a few days ago: http://pastebin.com/XhwSLCLA 

I am going to double/tripple check if I overlooked something, but I removed the old dir, then cloned it fresh, recompiled etc I don't understand this. Also pretty sure I am on the right branch/repo:

```
bash-4.3$ git remote -v
origin  https://github.com/justaphf/BitcoinUnlimited.git (fetch)
origin  https://github.com/justaphf/BitcoinUnlimited.git (push)
bash-4.3$ git status   
On branch 12.1initpriority
Your branch is up-to-date with 'origin/12.1initpriority'.
nothing to commit, working directory clean
```

**Comment by Justaphf** [comment]
@nomnombtc You'll want to wait a few minutes as I am performing some updates to this PR.  I was able to reproduce the issue you were seeing on Debian after rebasing on the latest 0.12.1bu commits and I think I have a fix for the new issues.  I've run the wallet test 5 times without error, however I want to run the full battery of tests again.  I'll post once I've finished pushing to this branch so you can see if it looks like Slackware is still having an issue.

EDIT: Push complete.  Please let me know if you run into issues on Slackware.  I will let you know if I see any issues after running the full suite of tests.

**Comment by Justaphf** [comment]
@nomnombtc With the last push make check and all the standard tests pass without error on my Debian machine.  I'm going to run the extended tests just to be sure.  Can you let me know if you still receive errors on your Slackware VM.  Hopefully this fixes it, but I have a feeling it will more likely just get you back to the original issue with just the newly introduced issue solved.

**Comment by nomnombtc** [comment]
@Justaphf allright, I can confirm it works fine on debian 8.6 vm after latest push ( 5de86d7 ), `make check` successfully completes, and I did run wallet.py test 10 times without any issue, no crash, no core dump. All good there. (I tested both, with `--enable-debug` and without it, both were fine)

On slackware64-14.2 vm even `make check` already fails with this error (I noticed this error also in travis build logs, for example [here](https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/170970056) when there is a red x besides a commit):
`test/transaction_tests.cpp(341): error: in "transaction_tests/test_IsStandard": check nDustThreshold == 546 has failed [0 != 546]`

and it still core dumps on slackware, exactly like in the previous post.

The only big difference (besides systemd and so on) between slackware14.2 and debian jessie, is boost gcc glibc (slackware has newer versions). So I cloned the debian vm and try to upgrade it to debian stretch (testing) and see what happens there.

**Comment by sickpig** [comment]
@nomnombtc @Justaphf 
just want to say that the aforementioned error `nDustThreshold == 546 has failed [0 != 546]` happens also on my forked repo (sickpig/BitcoinUnlimited) during Travis build of the "Win 64" binaries 

see the bottom of this file: 

https://s3.amazonaws.com/archive.travis-ci.org/jobs/170603896/log.txt

this seems to be unrelated to the issue at hand though.

**Comment by gandrewstone** [comment]
There are global variables sprinkled all over different files.  C++ only guarantees construction/destruction order for globals "with a translation unit" (i.e. a file).

Given that one global variable is a mutex that is taken/given whenever a bitcoin LOCK is used ( dd_mutex), and LOCK is used in ctors/dtors, its just lucky ordering by the compiler (and probably dev "guess-and-check" development methodology) that we are not seeing core dumps on startup/shutdown all the time.

I'm working on moving these globals into a single file so we can control the ctor/dtor ordering.

**Comment by nomnombtc** [comment]
@Justaphf tested also on debian stretch and it works fine there too, no problem! 
A summary of what I tried so far:

| OS | RESULT |
| --- | --- |
| Debian Jessie 64bit | make check ok, wallet.py runs fine |
| Debian Stretch 64bit | make check ok, wallet.py runs fine |
| OpenSUSE 42.1 64bit | make check ok, wallet.py runs fine |
| Slackware 14.1 64bit | make check fails, wallet.py segfaults |
| Slackware 14.2 64bit | make check fails, wallet.py segfaults |

I don't understand why it would not work on slackware...
_Edit: Added Result from test on OpenSUSE_

**Comment by Justaphf** [comment]
@nomnombtc I'm not sure why it is only affecting Slackware either.  I will try to install a Slackware VM over the weekend to see if I can debug into it further.  I've found some interesting results using the -fsanitize options (`-fsanitize=address,undefined`) which may be able to shed some additional light on the issue.

It looks like @gandrewstone is working on additional globals clean-ups, which may also resolve this issue.

If you want to try using the sanitizer compile options on your machine the following are the settings I have been using.  It's a quick and dirty script I wrote that may or may not work on your machine as I had to pull some of the other switches from the `./autogen.sh` generated configuration file, but you can probably check the configure file generated on your system and pull out the extra switches you need.  Just check the definition of the flags `LDFLAGS=`, `CPPFLAGS=`, `CFLAGS=`, and `CXXFLAGS=`

```
#!/bin/sh

# Check for changes on remote
git fetch origin

# NOTE: Don't switch branches, assume we are on the branch we want to test

# Make sure we are fully up to date on our current branch
git pull

# Update configuration (optional if you've already run it once)
./autogen.sh

# Ensure a clean build (optional if you aren't changing configure parameters)
make clean

# Configure (use statically linked BDB for wallet)
BDB_PREFIX=/home/debian/bin/BitcoinUnlimited/db4

# Use this line for standard compile
#./configure LDFLAGS="-L${BDB_PREFIX}/lib/" CPPFLAGS="-I${BDB_PREFIX}/include/"

# Use this line to compile in extra debugging instrumentation
./configure LDFLAGS="-fsanitize=undefined,address -L${BDB_PREFIX}/lib/" CPPFLAGS="-fsanitize=undefined,address -I${BDB_PREFIX}/include/" CXXFLAGS="-fsanitize=undefined,address -g -O2 -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wno-self-assign" CFLAGS="-fsanitize=undefined,address -g -O2"

# Build
make -j3

```

**Comment by sickpig** [comment]
@nomnombtc are you still able to reproduce this failure using the current 0.12.1bu branch after PR #140 and #138 has been merged?

@Justaphf is this PR still relevant or has been superseded by #140?

**Comment by Justaphf** [comment]
@sickpig The PR itself is no longer needed as all changes I made are superseded by the various globals.cpp commits.  I just hadn't closed because I still want to get a Slackware VM installed to see if I can reproduce @nomnombtc's issues.

If preferred I can close out this PR and open a different Issue ticket specifically for Slackware OS issues.

**Comment by sickpig** [comment]
@Justaphf great, please go ahead close this one and open another one when you'll be able to reproduce on slackware.
