### ISSUE TITLE
Build fails on FreeBSD 11

### ISSUE THREAD

**Issue by pamorris** [gandrewstone/bitcoin#571]
Release v1.0.2.0 won't build on FreeBSD 11. Fixed by @kyuupichan in PR #345. Only tested for FreeBSD 11 but builds and runs fine when applied to release v1.0.2.0.

**Comment by ftrader** [comment]
Thank you for confirming that @kyuupichan 's fix works for FreeBSD 11 on v1.0.2.0 .

Are you by any chance able to execute a run of the test suite on FreeBSD 11 and confirm if everything is alright or report if you get any failing tests?

From top of build tree:

`$ make check`  (unit tests)

`$ qa/pull-tester/rpc-tests.py`  (normal regression tests)

`$ qa/pull-tester/rpc-tests.py -extended-only`  (extended regression tests)

The last ones need  ~ 4GB free disk space and can take a long time.

There is also a chance that some tests might hang or loop indefinitely. Best to run overnight if you could, and log the output to a file.

**Comment by pamorris** [comment]
gmake check seems not to have run properly (util tests not found) and there are a few fails in the extended suite.

If I'm doing something wrong, let me know and I will run them again. 

[rpctests.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/999330/rpctests.txt)
[check.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/999331/check.txt)
[extended.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/999332/extended.txt)

**Comment by ftrader** [comment]
Can you confirm ~/BitcoinUnlimited/src/test/bitcoin-util-test.py is really missing?
This Python script is in version control in the source tree... it should not disappear under any circumstances.

'git status' should report it as missing it if disappeared, and 'git checkout src/test/bitcoin-util-test.py' should bring it back.

**Comment by pamorris** [comment]
The file is there in /src/test/. My guess was it had something to do with:

gmake[4]: Leaving directory '/usr/home/paul/BitcoinUnlimited/src'
Running test/bitcoin-util-test.py...
/bin/sh: ./test/bitcoin-util-test.py: not found

Leaving /src (presumably to the BitcoinUnlimited dir) and then looking for the file in ./test which it won't find.

I'm running 'gmake check' in the top directory - that's correct right? I also tried it in /src and /src/test but didn't seem to work either.

**Comment by ftrader** [comment]
>I'm running 'gmake check' in the top directory - that's correct right? I also tried it in /src and /src/test but didn't seem to work either.

That is the right way to run it... Cannot off-hand think of why it would fail.
Could you please upload your src/Makefile here for comparison?

Also, could you check what happens if you 'cd src' and run `gmake check` from there? (that works on my Linux box in the same way as 'make check' does from top level)

**Comment by pamorris** [comment]
I ran .autogen.sh, did a .configure again and 'gmake clean' and 'gmake all'. Same error. Tried in the /src folder and same again.

[Makefile.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/999602/Makefile.txt)

**Comment by ftrader** [comment]
I think you uploaded the top-level Makefile ?
The header in my src/Makefile indicates 'src/Makefile' on 2nd line.
Anyway, I'll have a look to see if I can discover a difference that might be causing it, but it would be helpful to have also src/Makefile to compare.

**Comment by pamorris** [comment]
Here is src/Makefile.

[Makefile.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/999636/Makefile.txt)

**Comment by ftrader** [comment]
Thanks for the Makefiles. So far I haven't spotted what could be causing it, so I decided to try and build on FreeBSD 11 to see if I can reproduce it.

I am running into a problem when it builds leveldb however:

```
In file included from .leveldb/port/port.h:14:
./leveldb/port/port_posix.h:38:12: fatal error: 'endian.h' file not found
   #include <endian.h>
```

~~Any idea how to get past this?~~ Nevermind, I probably just need to apply @kyuupichan 's PR first... yeah, that did it.

Running `gmake check` : I confirm your error related to bitcoin-util-test.py . Will look at it...

@sickpig : can we tag this issue with 'Bug' please ?

**Comment by unixtastic** [comment]
After applying the PR above this builds on FreeBSD 10.3-RELEASE-p11 but as above gmake check doesn't find bitcoin-util-test.py even though it does exist in the correct directory.

gmake[4]: Leaving directory '/usr/home/bc/BitcoinUnlimited/src'
Running test/bitcoin-util-test.py...
./test/bitcoin-util-test.py: not found

ls -l /usr/home/bc/BitcoinUnlimited/src/./test/bitcoin-util-test.py
-rwxr-xr-x  1 bc  bc  347 May 17 02:05 /usr/home/bc/BitcoinUnlimited/src/./test/bitcoin-util-test.py

**Comment by sickpig** [comment]
@unixtastic this is indeed weird. @kyuupichan what do you think the problem is?

**Comment by kyuupichan** [comment]
I don't know.  On DragonflyBSD make check seems to go into an infinite loop on script tests.  I have not had time to investigate.

**Comment by sickpig** [comment]
@pamorris have you ever tried to reproduce the error as of late?

Unfortunately I don't have any freebsd sys to try to reproduce. 

I'm going to close it for now. Feel free to re-open it, if this problem is present in the `release` branch.
