### ISSUE TITLE
Failure to compile dev HEAD with clang-3.8

### ISSUE THREAD

**Issue by awemany** [gandrewstone/bitcoin#1123]
The offending commit seems to be 24c60fe by @ptschip (potentially among others) . These are the error messages I get when compiling with `clang-3.8` using the extra flag `-std=c++14`:

```
In file included from net.cpp:25:
In file included from ./requestManager.h:31:
./nodestate.h:52:61: error: use of undeclared identifier 'cs_main'
extern std::map<NodeId, CNodeState> mapNodeState GUARDED_BY(cs_main);
                                                            ^
1 error generated.
Makefile:5688: recipe for target 'libbitcoin_server_a-net.o' failed
make[2]: *** [libbitcoin_server_a-net.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from nodestate.cpp:7:
./nodestate.h:52:61: error: use of undeclared identifier 'cs_main'
extern std::map<NodeId, CNodeState> mapNodeState GUARDED_BY(cs_main);
                                                            ^
1 error generated.
Makefile:5702: recipe for target 'libbitcoin_server_a-nodestate.o' failed
make[2]: *** [libbitcoin_server_a-nodestate.o] Error 1
main.cpp:71:40: error: expected ';' after top level declarator
CBlockIndex *pindexBestHeader = nullptr GUARDED_BY(cs_main);
                                       ^
                                       ;
main.cpp:71:41: warning: declaration does not declare anything [-Wmissing-declarations]
CBlockIndex *pindexBestHeader = nullptr GUARDED_BY(cs_main);
                                        ^
./threadsafety.h:18:23: note: expanded from macro 'GUARDED_BY'
#define GUARDED_BY(x) __attribute__((guarded_by(x)))
                      ^
main.cpp:91:28: error: expected ';' after top level declarator
int64_t nCoinCacheUsage = 0 GUARDED_BY(cs_main);
                           ^
                           ;
main.cpp:91:29: warning: declaration does not declare anything [-Wmissing-declarations]
int64_t nCoinCacheUsage = 0 GUARDED_BY(cs_main);
                            ^
./threadsafety.h:18:23: note: expanded from macro 'GUARDED_BY'
#define GUARDED_BY(x) __attribute__((guarded_by(x)))
                      ^
main.cpp:93:60: error: expected ';' after top level declarator
CFeeRate minRelayTxFee = CFeeRate(DEFAULT_MIN_RELAY_TX_FEE) GUARDED_BY(cs_main);
                                                           ^
                                                           ;
main.cpp:93:61: warning: declaration does not declare anything [-Wmissing-declarations]
CFeeRate minRelayTxFee = CFeeRate(DEFAULT_MIN_RELAY_TX_FEE) GUARDED_BY(cs_main);
                                                            ^
./threadsafety.h:18:23: note: expanded from macro 'GUARDED_BY'
#define GUARDED_BY(x) __attribute__((guarded_by(x)))
                      ^
main.cpp:147:41: error: expected ';' after top level declarator
CBlockIndex *pindexBestInvalid = nullptr GUARDED_BY(cs_main);
                                        ^
                                        ;
main.cpp:147:42: warning: declaration does not declare anything [-Wmissing-declarations]
CBlockIndex *pindexBestInvalid = nullptr GUARDED_BY(cs_main);
                                         ^
./threadsafety.h:18:23: note: expanded from macro 'GUARDED_BY'
#define GUARDED_BY(x) __attribute__((guarded_by(x)))
                      ^
main.cpp:175:30: error: expected ';' after top level declarator
uint64_t nBlockSequenceId = 1 GUARDED_BY(cs_main);
                             ^
                             ;
main.cpp:175:31: warning: declaration does not declare anything [-Wmissing-declarations]
uint64_t nBlockSequenceId = 1 GUARDED_BY(cs_main);
                              ^
./threadsafety.h:18:23: note: expanded from macro 'GUARDED_BY'
#define GUARDED_BY(x) __attribute__((guarded_by(x)))
                      ^
5 warnings and 5 errors generated.
Makefile:5646: recipe for target 'libbitcoin_server_a-main.o' failed
```

@sickpig confirmed this problem.

**Comment by awemany** [comment]
Fixed by #1125.
