### ISSUE TITLE
"./leakybucket.h:15:47: error: use of undeclared identifier 'LONG_LONG_MAX'" on FreeBSD

### ISSUE THREAD

**Issue by BlinkyStitt** [gandrewstone/bitcoin#38]
I'm trying to compile on FreeBSD 9.3 by following instructions that work for BitcoinXT (https://github.com/bitcoinxt/bitcoinxt/blob/master/doc/build-freebsd.md) but ran into an error.

```
In file included from ./unlimited.h:9:
./leakybucket.h:15:47: error: use of undeclared identifier 'LONG_LONG_MAX'
static const int64_t DEFAULT_MAX_RECV_BURST = LONG_LONG_MAX;
                                              ^
./leakybucket.h:17:47: error: use of undeclared identifier 'LONG_LONG_MAX'
static const int64_t DEFAULT_MAX_SEND_BURST = LONG_LONG_MAX;
                                              ^
./leakybucket.h:19:41: error: use of undeclared identifier 'LONG_LONG_MAX'
static const int64_t DEFAULT_AVE_RECV = LONG_LONG_MAX;
                                        ^
./leakybucket.h:21:41: error: use of undeclared identifier 'LONG_LONG_MAX'
static const int64_t DEFAULT_AVE_SEND = LONG_LONG_MAX;
                                        ^
./leakybucket.h:55:68: error: use of undeclared identifier 'LONG_LONG_MAX'
    CLeakyBucket(int64_t maxp, int64_t fillp, int64_t startLevel = LONG_LONG_MAX) : max(maxp), fill(fillp)
                                                                   ^
./leakybucket.h:66:16: error: use of undeclared identifier 'LONG_LONG_MAX'
        fill = LONG_LONG_MAX;
               ^
./leakybucket.h:67:15: error: use of undeclared identifier 'LONG_LONG_MAX'
        max = LONG_LONG_MAX;
              ^
./leakybucket.h:94:21: error: use of undeclared identifier 'LONG_LONG_MAX'
        if (fill == LONG_LONG_MAX)
                    ^
./leakybucket.h:95:20: error: use of undeclared identifier 'LONG_LONG_MAX'
            return LONG_LONG_MAX; // shaping is off
                   ^
./leakybucket.h:103:21: error: use of undeclared identifier 'LONG_LONG_MAX'
        if (fill == LONG_LONG_MAX)
                    ^
./leakybucket.h:117:21: error: use of undeclared identifier 'LONG_LONG_MAX'
        if (fill == LONG_LONG_MAX)
                    ^
11 errors generated.
Makefile:6110: recipe for target 'bitcoind-bitcoind.o' failed
gmake[2]: *** [bitcoind-bitcoind.o] Error 1
gmake[2]: Leaving directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
Makefile:7073: recipe for target 'all-recursive' failed
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
Makefile:652: recipe for target 'all-recursive' failed
gmake: *** [all-recursive] Error 1
```

A quick search found https://wiki.sagemath.org/freebsd/sage-4.3:

> sage/groups/perm_gps/permgroup_element.c fails to compile because LONG_LONG_MAX is not available on FreeBSD. Some googling suggests that this macro is either a GNU extension or is deprecated in C99 and has been replaced by LLONG_MAX - I have not been able to find a direct reference but indirect references include the following links: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=168346#19 http://linux.softpedia.com/progChangelog/GNU-ddrescue-Changelog-6106.html http://clang.llvm.org/doxygen/limits_8h-source.html

So I ran:

```
find . -name "*.h" -print0 | xargs -0 sed -i '' -e 's/LONG_LONG_MAX/LLONG_MAX/g'
find . -name "*.cpp" -print0 | xargs -0 sed -i '' -e 's/LONG_LONG_MAX/LLONG_MAX/g'
```

I'm not sure if this change should be done everywhere, or maybe inside some sort of conditional just on FreeBSD, but that simple change gets BU past this error on FreeBSD

**Comment by BlinkyStitt** [comment]
Latest master seems fixed:

```
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by BlinkyStitt** [comment]
Silly me. "Latest master" is not BU. This is still an issue.

**Comment by BlinkyStitt** [comment]
I'm pretty sure LLONG_MAX will work fine on linux too.

https://sourceware.org/bugzilla/show_bug.cgi?id=5461
https://www.gnu.org/software/libc/manual/html_node/Range-of-Type.html#Range-of-Type

> LONG_LONG_MIN
> LONG_LONG_MAX
> ULONG_LONG_MAX
> - These are obsolete names for LLONG_MIN, LLONG_MAX, and ULLONG_MAX. They are only available if _GNU_SOURCE is defined (see Feature Test Macros). In GCC versions prior to 3.0, these were the only names available.

**Comment by ftrader** [comment]
Confirmed the above replacement still needed and working on FreeBSD 11.0.
However, I looked at Core's issue tracker, there are a bunch of tickets for fixing builds on FreeBSD, but they seem to solve it in a different way. Latest Core 0.13, I don't see any LONG_LONG_MAX or LLONG_MAX in tree. Didn't check the commit history yet.

**Comment by sickpig** [comment]
@gandrewstone merged a @deadalnix  PR (#196) aimed to remove references of LONG_LONG_MAX from the code.  @WyseNynja would you mind to check if the issue is still there in the current 0.12.1bu branch?

**Comment by sickpig** [comment]
fixes #196

**Comment by sickpig** [comment]
@gandrewstone @AndrewClifford we can close this one IMHO.

**Comment by sickpig** [comment]
Should be fixed by #196. 
@WyseNynja if are able to reproduce the problem with current version of `release` please reopen
