### ISSUE TITLE
configure: WARNING: Could not resolve: -lqwindows; bitcoin-qt frontend will not be built

### ISSUE THREAD

**Issue by CCGLLC-knc** [gandrewstone/bitcoin#1219]
Attempted to build the bitcoin-qt wallet using an mingw environment under Windows 7.

I've built more current versions of most of the packages outlined in the build-windows-mingw document as you will see below.  Autogen.sh works without issue, however the .configure aborts the build of bitcoin-qt per the subject line.  ./configure is being invoked as:

```
CPPFLAGS="-I/c/deps/db-6.2.32.NC/build_unix \
-I/c/deps/openssl-1.0.2o/include \
-I/c/deps/libevent-2.0.22/include \
-I/c/deps \
-I/c/deps/protobuf-2.6.1/src \
-I/c/deps/libpng-1.6.34 \
-I/c/deps/qrencode-4.0.2" \
LDFLAGS="-L/c/deps/db-6.2.32.NC/build_unix \
-L/c/deps/openssl-1.0.2o \
-L/c/deps/libevent-2.0.22/.libs \
-L/c/deps/miniupnpc \
-L/c/deps/protobuf-2.6.1/src/.libs \
-L/c/deps/libpng-1.6.34/.libs \
-L/c/deps/qrencode-4.0.2/.libs" \
./configure \
--disable-upnp-default \
--disable-tests \
--with-qt-incdir=/c/Deps/QT/5.7.0/include \
--with-qt-libdir=/c/Deps/QT/5.7.0/lib \
--with-qt-plugindir=/c/Deps/QT/5.7.0/plugins \
--with-qt-bindir=/c/Deps/QT/5.7.0/bin \
--with-protoc-bindir=/c/deps/protobuf-2.6.1/src \
--with-incompatible-bdb
```

libqwindows.a is present in /c/deps/QT/5.7.0/plugins/platforms

QT was configured with:

`configure.bat -release -opensource -confirm-license -static -make libs -no-sql-sqlite -no-opengl -system-zlib -qt-pcre -no-icu -no-gif -system-libpng -no-libjpeg -no-freetype -no-angle -openssl -no-dbus -no-audio-backend -no-wmf-backend -no-qml-debug -I c:\deps\libpng-1.6.34 -I c:\deps\openssl-1.0.2o\include -L c:\deps\libpng-1.6.34\.libs -L c:\deps\openssl-1.0.2o`

**Comment by sickpig** [comment]
paging @ptschip @Justaphf

**Comment by ptschip** [comment]
I don't use QT5.7, but sometimes it does happen that configure will fail on native windows, and what I usually do is run it again and then it's fine.  Not sure why it does that, some bug in windows or perhaps windows defender... i have noticed that when turning off any kind of virus detection that configure runs much faster on windows.  Anyway, I would try running it a few times, if you haven't already done that.

**Comment by CCGLLC-knc** [comment]
Will try again.  I can confirm the anti-virus slowdown.  I'm currently (and not for much longer) running Avast and I see hundreds of popups - mostly during the "checking..." phases.

**Comment by Justaphf** [comment]
@ccgllc-rbtc Were you able to get the dependency upgrades working after disabling A/V and retrying as @ptschip said?  I've never run into the issue you describe, but I've also never successfully gotten updated versions of the various dependencies working.  Granted I've only halfheartedly attempted to upgrade the dependencies for native Windows MinGW builds and ran into issues and put it aside to work on other things.

If you were able to figure out the correct versions and config settings to use that would be great if you could provide those.  I'd be willing to go through and update both the windows build documentation and the semi-automated build scripts under the ./build-aux/mingw folder if you didn't feel like putting in a PR yourself.

**Comment by CCGLLC-knc** [comment]
I'm expecting to get back to that effort next week.  I'll keep you posted via this thread.

**Comment by sickpig** [comment]
@ccgllc-rbtc any heads up?

**Comment by CCGLLC-knc** [comment]
Sorry folks, finally carved some time out to get back on this.  RL interferred, you don't want the details.

Started with a "git pull", just to make sure I had the most current source.  Spotted a Warning about makensis not being found, so fixed that.

Thinking this might be QT build related, I found a patch and built 5.7.1 without error.  Made a couple of configure.bat changes, like using -qt-libpng  to reduce dependencies on other packages.  Also added -qt-libjpeg to address that assumption in the Configure.

Configure then generated a  "WARNING: libQt5PlatformSupport not found;" warning and stated the front end will not be built.

Backed off to 5.7.0 and getting the same problem.

For hells bells, tried 5.11.2 and have the same problem (and QTTools doesn't build)

Suggestions?

**Comment by ptschip** [comment]
I use qt 5.3.2

**Comment by CCGLLC-knc** [comment]
5.3.2 does indeed make it through the configure step, I suspect since it goes through the "QT < 5.4" path.  Had problems with DB-6.2.32.NC - it compiled fine, but bitcoin's compilation failed with DB related errors.  DB-5.3.28-NC worked fine.  So a successful build uses this combination of components:

`CPPFLAGS="-I/c/deps/db-5.3.28.NC/build_unix \
-I/c/deps/openssl-1.0.2o/include \
-I/c/deps/libevent-2.0.22/include \
-I/c/deps \
-I/c/deps/protobuf-2.6.1/src \
-I/c/deps/libpng-1.6.34 \
-I/c/deps/qrencode-4.0.2" \
LDFLAGS="-L/c/deps/db-5.3.28.NC/build_unix \
-L/c/deps/openssl-1.0.2o \
-L/c/deps/libevent-2.0.22/.libs \
-L/c/deps/miniupnpc \
-L/c/deps/protobuf-2.6.1/src/.libs \
-L/c/deps/libpng-1.6.34/.libs \
-L/c/deps/qrencode-4.0.2/.libs" \
./configure \
--disable-upnp-default \
--disable-tests \
--with-qt-incdir=/c/Deps/QT/5.3.2/include \
--with-qt-libdir=/c/Deps/QT/5.3.2/lib \
--with-qt-plugindir=/c/Deps/QT/5.3.2/plugins \
--with-qt-bindir=/c/Deps/QT/5.3.2/bin \
--with-protoc-bindir=/c/deps/protobuf-2.6.1/src \
--with-incompatible-bdb`

QT was built using:
`configure.bat -release -opensource -confirm-license -static -make libs -nomake tests -nomake examples -no-sql-sqlite -no-opengl -qt-zlib -qt-pcre -no-icu -no-gif -qt-libpng -qt-libjpeg -no-freetype -qt-zlib -no-angle -openssl -no-dbus -no-audio-backend -no-wmf-backend -no-qml-debug -I c:\deps\openssl-1.0.2o\include -L c:\deps\openssl-1.0.2o`

Still fooling around to see if I can get 5.7.1 to work since that is what Bitcoin Core ships with.  If they did it, we should be abler to as well!

**Comment by ptschip** [comment]
glad you got it working, and yes if you can get it to work on 5.7 that
would be great :)

**Comment by CCGLLC-knc** [comment]
Regarding 5.7.1, currently stuck with the warning about no main in Qt5PlatformSupport:

`checking for main in -lQt5Core   ... yes
checking for main in -lQt5Gui    ... yes
checking for main in -lQt5Network... yes
checking for main in -lQt5Widgets... yes
checking for main in -lQt5Test... yes
checking QTest usability... yes
checking QTest presence... yes
checking for QTest... yes
checking for main in -lQt5DBus... no
checking QtDBus usability... no
checking QtDBus presence... no
checking for QtDBus... no
checking for static Qt... yes
checking for Qt >= 5.6... yes
checking for main in -lQt5PlatformSupport... no
configure: WARNING: libQt5PlatformSupport not found; bitcoin-qt frontend will no
t be built
checking for Qt < 5.4... no
checking for static Qt plugins: -lqwindows... no`

Note however that libQt5PlatformSupport.a exists in the 5.7.1/lib folder (along with Qt5Core and the others I included in the paste above).  So this doesn't feel like an issue building QT, but rather something in the configure script?  On the flip side, the same configure script finds the file if pointed at a QT 5.3.2 build.  Checked and the 5.3.2 version is 89kb and the 5.7.1 is 140kb (e.g. the file isn't empty).  

Rather confused.  Any suggestions?

**Comment by CCGLLC-knc** [comment]
... and got around it by including an additional:
`-L/c/deps/QT/5.7.1/lib \`
In the configure command.  That despite having:
`--with-qt-libdir=/c/Deps/QT/5.7.1/lib \`

... and SUCCESS!  Bitcoin compiled fine and the executable launched without issue (beyond my stupid Anti-Virus blocking it).

Updated build instructions attached.
[build-windows-mingw.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/2412354/build-windows-mingw.txt)

**Comment by CCGLLC-knc** [comment]
Addendum:  Striping the bitcoin-qt.exe reduces its size from 447,176kb to 28,529kb.

**Comment by ptschip** [comment]
awesome...

can you open a PR?

**Comment by CCGLLC-knc** [comment]
... have never done that.  Care to walk me through it?

**Comment by ptschip** [comment]
that may take a while...you'd have to have a github account with a fork
of BU...and you'd need git installed locally with the BU repo cloned.  
It's a process if you've never done it before...

if you don't have the time I can open the PR for you...just let me know.

**Comment by ptschip** [comment]
of course , its good to learn and do it yourself, AND, you'll show up in
git with credits as the author :)

**Comment by CCGLLC-knc** [comment]
I use git a fair amount (I've authored 3 coins back in 2014, and playing with the DAA for a new one now), so git I have, and git I used to clone bitcoinunlimited source.  Sounds like something I should take a stab at when I get some time.
